// scripts/typegen.mjs
import { generateTypes } from "@sanity/codegen";
import fs from "fs";

// Load the schema.json that was generated by "sanity schema extract"
const schema = JSON.parse(fs.readFileSync("./schema.json", "utf-8"));

// Generate types
generateTypes({
  schema,
  typesOutputPath: "./sanity.types.d.ts", // output file
});
